// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"clean-arq-struct/internal/domain/gateway"
	"clean-arq-struct/internal/event"
	"clean-arq-struct/internal/infra/database"
	"clean-arq-struct/internal/infra/web"
	"clean-arq-struct/internal/usecase"
	"clean-arq-struct/pkg/events"
	"database/sql"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewCreateOrderUsecase(db *sql.DB, evDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := repository.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, evDispatcher, orderCreated)
	return createOrderUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := repository.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderCreated)
	return webOrderHandler
}

// wire.go:

var setRepositoryDependency = wire.NewSet(repository.NewOrderRepository, wire.Bind(new(gateway.OrderRepositoryInterface), new(*repository.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))
